// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Chaso.Push.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Class for Send and receive a Notification
    /// </summary>
    public partial class Notify
    {
        /// <summary>
        /// Initializes a new instance of the Notify class.
        /// </summary>
        public Notify() { }

        /// <summary>
        /// Initializes a new instance of the Notify class.
        /// </summary>
        public Notify(string origin = default(string), string channel = default(string), string eventName = default(string), object data = default(object))
        {
            Origin = origin;
            Channel = channel;
            EventName = eventName;
            Data = data;
        }

        /// <summary>
        /// Origin of interation on channel
        /// </summary>
        [JsonProperty(PropertyName = "Origin")]
        public string Origin { get; set; }

        /// <summary>
        /// Nome of the Channel to interact
        /// </summary>
        [JsonProperty(PropertyName = "Channel")]
        public string Channel { get; set; }

        /// <summary>
        /// Name of Evento to execute in Channel
        /// </summary>
        [JsonProperty(PropertyName = "EventName")]
        public string EventName { get; set; }

        /// <summary>
        /// Object to Send and Receive by Notification
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public object Data { get; set; }

    }
}
